apiVersion: apps/v1
kind: Deployment
metadata:
  name: shortenerurl-deployment
  labels:
    app: shortenerurl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: shortenerurl
  template:
    metadata:
      labels:
        app: shortenerurl
    spec:
      containers:
        - name: shortenerurl-server
          image: disconhecido/urlshortener-test:lastest
          ports:
            - containerPort: 88


---

apiVersion: v1
kind: Service
metadata:
  name: urlshortener-test-service
spec:
  selector:
    app: shortenerurl
  type: NodePort
  ports:
    - protocol: TCP
      port: 88
      targetPort: 88